services:
  # Traefik Development
  orbitto_traefik:
    ports:
      - "${ORBITTO_TRAEFIK_EXPOSE_HTTP_PORT:-80}:80"
      - "${ORBITTO_TRAEFIK_EXPOSE_DASHBOARD_PORT:-8080}:8080" # Web UI

  # PostgreSQL Development
  orbitto_kratos_db:
    ports:
      - "${ORBITTO_KRATOS_DB_EXPOSE_HTTP_PORT:-5432}:5432"

  # Kratos Development
  orbitto_kratos:
    ports:
      - "${ORBITTO_KRATOS_EXPOSE_PUBLIC_PORT:-4433}:4433" # Public
      - "${ORBITTO_KRATOS_EXPOSE_ADMIN_PORT:-4434}:4434" # Admin
    environment:
      DSN: memory # use in-memory database for development
      LOG_LEVEL: ${ORBITTO_KRATOS_LOG_LEVEL:-info}
      # leak sensitive values to log for development
      LOG_LEAK_SENSITIVE_VALUES: true
    command: serve -c /etc/config/kratos/kratos.yaml --dev --watch-courier
    depends_on: {}

  orbitto_web:
    # use same user to be able
    build:
      context: ./web
      dockerfile: ../infra/docker/web/Dockerfile.dev
      args:
        DIR: ${PWD}/web # for better path mapping with host
    image: orbitto_web:dev
    ports:
      - "${ORBITTO_WEB_HOTRELOAD_PORT:-5173}:5173"
      - "${ORBITTO_WEB_EXPOSE_PORT:-3000}:3000"
    volumes:
      - ./web:${PWD}/web:cached
      - orbitto_web_node_modules:${PWD}/web/node_modules
    command: sh -c "pnpm install && pnpm run dev"
    environment:
      NODE_ENV: development
      CI: true

  orbitto_core:
    build:
      context: .
      dockerfile: infra/docker/core/Dockerfile.dev
      args:
        DIR: ${PWD}
    ports:
      - "${ORBITTO_CORE_EXPOSE_PORT:-8081}:8080"
    volumes:
      - ${PWD}:${PWD}

  orbitto_mailpit:
    ports:
      - ${ORBITTO_MAILPIT_EXPOSE_PORT:-8025}:8025

volumes:
  orbitto_web_node_modules: {}
