package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	graphql1 "github.com/kfreiman/engineer-challenge/internal/bff/ports/graphql"
	"github.com/kfreiman/engineer-challenge/internal/bff/ports/graphql/model"
	"github.com/kfreiman/engineer-challenge/internal/bff/ports/http/middleware"
	"github.com/kfreiman/engineer-challenge/internal/profile/app/query"
)

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (model.UpdateProfileResult, error) {
	panic(fmt.Errorf("not implemented: UpdateProfile - updateProfile"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (model.MeResult, error) {
	identityID := middleware.GetIdentityID(ctx)
	if identityID == "" {
		r.Logger.WarnContext(ctx, "unauthenticated request to Me")
		return model.UnauthenticatedError{
			Message: "Unauthorized",
		}, nil
	}

	r.Logger.DebugContext(ctx, "getting profile", "identity_id", identityID)
	ent, err := r.ProfileApp.Queries.GetProfile.Handle(ctx, query.GetProfile{
		IdentityID: identityID,
	})
	if err != nil {
		r.Logger.ErrorContext(ctx, "failed to get profile", "identity_id", identityID, "error", err)
		return nil, err
	}

	return mapProfileToUserDTO(ctx, ent, r.BillingApp)
}

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
