package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	graphql1 "github.com/kfreiman/engineer-challenge/internal/bff/ports/graphql"
	entity1 "github.com/kfreiman/engineer-challenge/internal/billing/domain/entity"
	"github.com/kfreiman/engineer-challenge/internal/profile/domain/entity"
)

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, fullName string) (*entity.Profile, error) {
	panic(fmt.Errorf("not implemented: UpdateProfile - updateProfile"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*entity.Profile, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*entity.Profile, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Plan is the resolver for the plan field.
func (r *subscriptionResolver) Plan(ctx context.Context) (<-chan entity1.Plan, error) {
	panic(fmt.Errorf("not implemented: Plan - plan"))
}

// Status is the resolver for the status field.
func (r *subscriptionResolver) Status(ctx context.Context) (<-chan entity1.Status, error) {
	panic(fmt.Errorf("not implemented: Status - status"))
}

// ExpiresAt is the resolver for the expiresAt field.
func (r *subscriptionResolver) ExpiresAt(ctx context.Context) (<-chan *string, error) {
	panic(fmt.Errorf("not implemented: ExpiresAt - expiresAt"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *subscriptionResolver) CreatedAt(ctx context.Context) (<-chan string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *entity.Profile) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *entity.Profile) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *entity.Profile) (string, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

// Subscription returns graphql1.SubscriptionResolver implementation.
func (r *Resolver) Subscription() graphql1.SubscriptionResolver { return &subscriptionResolver{r} }

// User returns graphql1.UserResolver implementation.
func (r *Resolver) User() graphql1.UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
