# Stage 1: Modules caching
FROM golang:1.26.1-alpine3.22 AS modules
ARG DIR
WORKDIR ${DIR}

COPY go.mod go.sum ${DIR}/
RUN go mod download

# Stage 2: Builder
FROM golang:1.26.1-alpine3.22 AS builder

RUN go install github.com/air-verse/air@latest

ARG DIR
WORKDIR ${DIR}

COPY . .

# Command to run air
ENV GOFLAGS="-buildvcs=false"
ENTRYPOINT ["air", "-c", ".air.toml"]