/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionRouteImport } from './routes/_session'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthSettingsRouteImport } from './routes/auth/settings'
import { Route as AuthRegistrationRouteImport } from './routes/auth/registration'
import { Route as AuthRecoveryRouteImport } from './routes/auth/recovery'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as SessionProfileRouteImport } from './routes/_session/profile'

const SessionRoute = SessionRouteImport.update({
  id: '/_session',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/auth/settings',
  path: '/auth/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegistrationRoute = AuthRegistrationRouteImport.update({
  id: '/auth/registration',
  path: '/auth/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoveryRoute = AuthRecoveryRouteImport.update({
  id: '/auth/recovery',
  path: '/auth/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionProfileRoute = SessionProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SessionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof SessionProfileRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/registration': typeof AuthRegistrationRoute
  '/auth/settings': typeof AuthSettingsRoute
  '/auth/verify': typeof AuthVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof SessionProfileRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/registration': typeof AuthRegistrationRoute
  '/auth/settings': typeof AuthSettingsRoute
  '/auth/verify': typeof AuthVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_session': typeof SessionRouteWithChildren
  '/_session/profile': typeof SessionProfileRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/registration': typeof AuthRegistrationRoute
  '/auth/settings': typeof AuthSettingsRoute
  '/auth/verify': typeof AuthVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/auth/error'
    | '/auth/login'
    | '/auth/recovery'
    | '/auth/registration'
    | '/auth/settings'
    | '/auth/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/auth/error'
    | '/auth/login'
    | '/auth/recovery'
    | '/auth/registration'
    | '/auth/settings'
    | '/auth/verify'
  id:
    | '__root__'
    | '/'
    | '/_session'
    | '/_session/profile'
    | '/auth/error'
    | '/auth/login'
    | '/auth/recovery'
    | '/auth/registration'
    | '/auth/settings'
    | '/auth/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionRoute: typeof SessionRouteWithChildren
  AuthErrorRoute: typeof AuthErrorRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecoveryRoute: typeof AuthRecoveryRoute
  AuthRegistrationRoute: typeof AuthRegistrationRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_session': {
      id: '/_session'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/settings': {
      id: '/auth/settings'
      path: '/auth/settings'
      fullPath: '/auth/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/registration': {
      id: '/auth/registration'
      path: '/auth/registration'
      fullPath: '/auth/registration'
      preLoaderRoute: typeof AuthRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recovery': {
      id: '/auth/recovery'
      path: '/auth/recovery'
      fullPath: '/auth/recovery'
      preLoaderRoute: typeof AuthRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_session/profile': {
      id: '/_session/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SessionProfileRouteImport
      parentRoute: typeof SessionRoute
    }
  }
}

interface SessionRouteChildren {
  SessionProfileRoute: typeof SessionProfileRoute
}

const SessionRouteChildren: SessionRouteChildren = {
  SessionProfileRoute: SessionProfileRoute,
}

const SessionRouteWithChildren =
  SessionRoute._addFileChildren(SessionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionRoute: SessionRouteWithChildren,
  AuthErrorRoute: AuthErrorRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRecoveryRoute: AuthRecoveryRoute,
  AuthRegistrationRoute: AuthRegistrationRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
