# yaml-language-server: $schema=https://raw.githubusercontent.com/traefik/traefik/v3.0/docs/content/reference/dynamic-configuration/file.json
http:
  routers:
    bff:
      rule: PathPrefix(`/bff`)
      service: bff
      entryPoints:
        - web
      priority: 2
  services:
    bff:
      loadBalancer:
        servers:
          - url: http://orbitto_core:8080
